### ISSUE TITLE
fail to download PyTorch models

### ISSUE THREAD

**Issue by elf55** [Ruqyai/falcon-40b#1]
When I try a simple git clone of this repo, the clone fails with the error:

`Downloading pytorch_model-00001-of-00009.bin (9.5 GB)
Error downloading object: pytorch_model-00001-of-00009.bin (384bd92): Smudge error: Error downloading pytorch_model-00001-of-00009.bin (384bd92e6d1d0b6a133b1d81bad915a10d954d1bfcdf4fdc8b6d0d81b4f5e9e8): [384bd92e6d1d0b6a133b1d81bad915a10d954d1bfcdf4fdc8b6d0d81b4f5e9e8] Object does not exist on the server: [404] Object does not exist on the server`

It looks like this model file isn't available through the lfs link.

**Comment by Ruqyai** [comment]
Hi @elf55 

Try this:
```
git lfs install
git clone https://huggingface.co/tiiuae/falcon-40b
```

**Comment by elf55** [comment]
I can clone from the huggingface site repo.   But the lfs links on github don’t.

**Comment by Ruqyai** [comment]
Actually, you don't need the Github. 
Clone/download directly from Huggingface to your notebook and check if your RAM and space are enough
